services:
  backend:
    build: backend
    working_dir: /backend
    command: sleep infinity
    ports:
    - "8080:8080"
    volumes:
      - ./backend:/backend
      - ./frontend/dist/aas-business-card/browser:/backend/src/main/resources/static:ro
  frontend:
    image: node:23.11
    working_dir: /frontend
    command: sleep infinity
    volumes:
      - ./frontend:/frontend
  db:
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=app
      - POSTGRES_DB=app_db
volumes:
  db_data:
