services:
  backend:
    build: .
    ports:
    - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=app
      - POSTGRES_DB=app_db
  db:
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=app
      - POSTGRES_DB=app_db
volumes:
  db_data:
