services:
  app:
    build: .
    ports:
    - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=app
      - POSTGRES_DB=app_db
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP"
      interval: 5s
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=app
      - POSTGRES_DB=app_db
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
volumes:
  db_data:
