name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Python dependencies
        run: pip install 'requests>=2.32' 'aas_test_engines==1.0.2'
      - name: Build the Docker image
        run: docker compose -f compose.prod.yml build
      - name: Run integration Tests
        run: docker compose up -d && ./bin/integration_test.py
