name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Python dependencies
        run: pip install 'requests>=2.32' 'aas_test_engines==1.0.2'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker compose -f compose.prod.yml build
      - name: Run integration Tests
        run: docker compose -f compose.prod.yml up -d --wait && ./bin/integration_test.py
      - name: Publish Image
        run: docker push ghcr.io/otto-ifak/aas-business-card:latest
